/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diss3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import simulation.Minibus;
import simulation.MySimulation;
import OSPABA.ISimDelegate;
import OSPABA.SimState;
import OSPABA.Simulation;
import java.util.function.Consumer;

/**
 *
 * @author davidecek
 */
public class GUI extends javax.swing.JFrame implements ISimDelegate {

    private DefaultTableModel dtm;
    private MySimulation mySim;

    /**
     * Creates new form GUI
     */
    public GUI() {
        String col[] = {"Cislo Minibusu", "Pozicia 1"};
        dtm = new DefaultTableModel(col, 0);
        mySim = new MySimulation();
        mySim.registerDelegate(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        nadpis = new javax.swing.JLabel();
        Turbo = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pocetZamSim = new javax.swing.JTextField();
        pocMinSim = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vyslTerm1 = new javax.swing.JLabel();
        vyslTerm2 = new javax.swing.JLabel();
        vyslTerm3 = new javax.swing.JLabel();
        vyslCasTerm1 = new javax.swing.JLabel();
        vyslCasTerm2 = new javax.swing.JLabel();
        vyslVytazenost = new javax.swing.JLabel();
        vyslCasObsluha = new javax.swing.JLabel();
        vyslCasSystem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        spomalenie = new javax.swing.JSlider();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pocZamTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pocMinibusTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pocReplText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priemCasTerm1Lab = new javax.swing.JLabel();
        priemCasTerm2Lab = new javax.swing.JLabel();
        priemCasObsluhaLab = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        celkCasVSysteme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        obsluhaLabel = new javax.swing.JLabel();
        term2Label = new javax.swing.JLabel();
        term1Label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vytPracovnikov = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        intSpol = new javax.swing.JLabel();
        panelGraf1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nadpis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nadpis.setText("Turbo mód");

        Turbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TurboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TurboMousePressed(evt);
            }
        });

        jLabel14.setText("Pocet zamestnancov:");

        jLabel15.setText("Pocet minibusov:");

        pocetZamSim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocetZamSim.setText("1");
        pocetZamSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocetZamSimActionPerformed(evt);
            }
        });

        pocMinSim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocMinSim.setText("1");
        pocMinSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocMinSimActionPerformed(evt);
            }
        });

        jLabel16.setText("pocet ludi terminal 1:");

        jLabel17.setText("pocet ludi terminal 2:");

        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setText("pocet ludi pred obsluhou:");

        jLabel19.setText("priemerny cas v rade term 1:");

        jLabel20.setText("priemerny cas v rade term 2:");

        jLabel21.setText("vytazenost pracovnikov:");

        jLabel22.setText("priemerny cas v rade pred obsluhou:");

        jLabel23.setText("celkovy cas cestujuceho v systeme:");

        vyslTerm1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm1.setText("0");

        vyslTerm2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm2.setText("0");

        vyslTerm3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm3.setText("0");

        vyslCasTerm1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasTerm1.setText("0");

        vyslCasTerm2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasTerm2.setText("0");

        vyslVytazenost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslVytazenost.setText("0");

        vyslCasObsluha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasObsluha.setText("0");

        vyslCasSystem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasSystem.setText("0");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cislo Minibusu", "Pozicia 1", "% z trate", "Pozicia 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel24.setText("Simulacny cas:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("00.00.00 - 00:00:00");

        spomalenie.setValue(0);

        jButton4.setText("prerus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pocetZamSim)
                                            .addComponent(pocMinSim, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel21))
                                        .addGap(118, 118, 118)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vyslVytazenost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasTerm2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasObsluha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spomalenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pocetZamSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(pocMinSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(vyslTerm1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(vyslTerm2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(vyslTerm3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(vyslCasTerm1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(vyslCasTerm2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(vyslCasObsluha))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(vyslVytazenost))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(vyslCasSystem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addComponent(spomalenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Turbo.addTab("Simulacia", jPanel2);

        jLabel6.setText("Pocet Zamestnancov:");

        pocZamTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocZamTextField.setText("18");
        pocZamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocZamTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Pocet Minibusov:");

        pocMinibusTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocMinibusTextField.setText("7");

        jButton1.setText("Spusti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Pocet Replikacii:");

        pocReplText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocReplText.setText("100");

        jButton2.setText("prerus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("priemerny cas v rade term 1:");

        jLabel9.setText("priemerny cas v rade term 2:");

        jLabel10.setText("priemerny cas v rade pred obsluhou:");

        priemCasTerm1Lab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasTerm1Lab.setText("0");

        priemCasTerm2Lab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasTerm2Lab.setText("0");

        priemCasObsluhaLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasObsluhaLab.setText("0");

        jLabel11.setText("celkovy cas cestujuceho v systeme:");

        celkCasVSysteme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celkCasVSysteme.setText("0");

        jLabel2.setText("pocet ludi terminal 1:");

        jLabel3.setText("pocet ludi terminal 2:");

        jLabel5.setText("pocet ludi pred obsluhou:");

        obsluhaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        obsluhaLabel.setText("0");

        term2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        term2Label.setText("0");

        term1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        term1Label.setText("0");

        jLabel12.setText("vytazenost pracovnikov:");

        vytPracovnikov.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vytPracovnikov.setText("0");

        jLabel1.setText("interval spolahlivosti:");

        intSpol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intSpol.setText("<0;0>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pocReplText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pocMinibusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(pocZamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)
                        .addComponent(priemCasTerm2Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addComponent(priemCasTerm1Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(obsluhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(term2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(term1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celkCasVSysteme, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vytPracovnikov, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priemCasObsluhaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intSpol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocZamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(term1Label)
                    .addComponent(jLabel10)
                    .addComponent(priemCasObsluhaLab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocMinibusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(term2Label)
                    .addComponent(jLabel12)
                    .addComponent(vytPracovnikov))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocReplText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(obsluhaLabel)
                    .addComponent(jLabel11)
                    .addComponent(celkCasVSysteme))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(priemCasTerm1Lab)
                    .addComponent(jLabel1)
                    .addComponent(intSpol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(priemCasTerm2Lab))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        Turbo.addTab("Turbo mod", jPanel1);

        jButton5.setText("Vykresli");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGraf1Layout = new javax.swing.GroupLayout(panelGraf1);
        panelGraf1.setLayout(panelGraf1Layout);
        panelGraf1Layout.setHorizontalGroup(
            panelGraf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(1007, Short.MAX_VALUE))
        );
        panelGraf1Layout.setVerticalGroup(
            panelGraf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        Turbo.addTab("Graf zavislosti", panelGraf1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nadpis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Turbo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nadpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Turbo)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TurboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurboMousePressed

    }//GEN-LAST:event_TurboMousePressed

    private void TurboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurboMouseClicked
        nadpis.setText("Turbo mód");
    }//GEN-LAST:event_TurboMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void pocZamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocZamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocZamTextFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int pocetAut = Integer.parseInt(pocMinSim.getText());
        int pocetPracovnikov = Integer.parseInt(pocetZamSim.getText());
        int pocetReplikacii = 10000;//Integer.parseInt(pocReplText.getText());      

        mySim.setPocetMinibusov(pocetAut);
        mySim.setPocetPracovnikov(pocetPracovnikov);
        mySim.onReplicationWillStart(new Consumer<Simulation>() {
            @Override
            public void accept(Simulation sim) {
                sim.setSimSpeed(0, 0);
            }
        }
        );

        for (int i = 0;
                i < pocetAut;
                i++) {
            dtm.addRow(new Object[]{i, "", "", ""});
            dtm.setValueAt(i, i, 0);
        }

        mySim.simulate(pocetReplikacii,
                4.5 * 60 * 60);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pocetZamSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocetZamSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocetZamSimActionPerformed

    private void pocMinSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocMinSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocMinSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Turbo;
    private javax.swing.JLabel celkCasVSysteme;
    private javax.swing.JLabel intSpol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nadpis;
    private javax.swing.JLabel obsluhaLabel;
    private javax.swing.JPanel panelGraf1;
    private javax.swing.JTextField pocMinSim;
    private javax.swing.JTextField pocMinibusTextField;
    private javax.swing.JTextField pocReplText;
    private javax.swing.JTextField pocZamTextField;
    private javax.swing.JTextField pocetZamSim;
    private javax.swing.JLabel priemCasObsluhaLab;
    private javax.swing.JLabel priemCasTerm1Lab;
    private javax.swing.JLabel priemCasTerm2Lab;
    private javax.swing.JSlider spomalenie;
    private javax.swing.JLabel term1Label;
    private javax.swing.JLabel term2Label;
    private javax.swing.JLabel vyslCasObsluha;
    private javax.swing.JLabel vyslCasSystem;
    private javax.swing.JLabel vyslCasTerm1;
    private javax.swing.JLabel vyslCasTerm2;
    private javax.swing.JLabel vyslTerm1;
    private javax.swing.JLabel vyslTerm2;
    private javax.swing.JLabel vyslTerm3;
    private javax.swing.JLabel vyslVytazenost;
    private javax.swing.JLabel vytPracovnikov;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(Simulation simulation) {
        MySimulation mySim = (MySimulation) simulation;
        this.vyslVytazenost.setText(String.valueOf(mySim.agentObsluhy().getPocetVytazenychPracovnikov()));
//        Minibus[] minibusy = mySim.getMinibusy();
//
//        if (minibusy != null) {
//            for (int i = 0; i < minibusy.length; i++) {
//                dtm.setValueAt(minibusy[i].getCisloMinibusu(), i, 1);
//                int pom = minibusy[i].getPolohaMinibusu();
//                String pom2 = "";
//                if (pom == 0) {
//                    pom2 = "Terminal-1";
//                } else if (pom == 1) {
//                    pom2 = "Terminal-2";
//                } else if (pom == 2) {
//                    pom2 = "Arcar";
//                } else if (pom == 3) {
//                    pom2 = "Terminal-3";
//                }
//                dtm.setValueAt(pom2, i, 3);
//            }
//            this.jTable1.setModel(dtm);
//        } else {
//            JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
//        }
    }

    public void vykresli(double priemer, double counter, double horna, double spodna) {

    }

    @Override
    public void simStateChanged(Simulation smltn, SimState ss) {
    }

}
